[tools]
aws-cli = "2.36.22"
direnv = "2.37.1"
erlang = "27.3"
java = "corretto-21.0.11.10.1"
node = "24.11.1"
python = "3.12.2"
rclone = "1.75.0"
ruby = "4.0.5"
terraform = "1.7.4"
yarn = "1.22.19"

[settings.python]
github_attestations = false
